version: "3.7"

networks:
    lookoutstationnet:
        external: false
        name: lookoutstationnet
        driver: bridge
    web:
        external: true


services:
    database:
        image: postgres:12
        container_name: lookoutstation-database
        hostname: database
        networks:
            - lookoutstationnet
        env_file:
            - configs/postgres.env

    redis:
      image: redis:latest
      container_name: lookoutstation-redis
      hostname: redis
      networks:
        - lookoutstationnet

    api:
        build: api/
        image: lookoutstation-api:latest
        container_name: lookoutstation-api
        hostname: lookoutstation-api
        networks:
            - lookoutstationnet
            - web
        ports:
            - "8080"
        env_file:
            - configs/postgres.env
        environment:
            - FLASK_APP=main.py
        depends_on:
            - database
        labels:
            - traefik.backend=blog
            - traefik.frontend.rule=Host:api.lookout.network
            - traefik.docker.network=web
            - traefik.port=8080

    emailer:
        build: emailer/
        image: lookoutstation-emailer:latest
        container_name: lookoutstation-emailer
        hostname: lookoutstation-emailer
        networks:
            - lookoutstationnet
        env_file:
            - configs/email.env
        depends_on:
            - api

    frontend:
        build: frontend/
        image: lookoutstation-frontend:latest
        container_name: lookoutstation-frontend
        hostname: lookoutstation-frontend
        environment:
            - API=https://api.lookout.network/
        networks:
            - lookoutstationnet
            - web
        ports:
            - "80"
        depends_on:
            - api
        labels:
            - traefik.backend=frontend
            - traefik.frontend.rule=Host:lookout.network
            - traefik.docker.network=web
            - traefik.port=80

    worker-api:
        build: worker-api/
        image: lookoutstation-worker-api:latest
        container_name: lookoutstation-worker-api
        hostname: lookoutstation-worker-api
        networks:
            - lookoutstationnet
        depends_on:
            - redis
            - api

    worker:
        build: worker/
        image: lookoutstation-worker:latest
        container_name: lookoutstation-worker
        hostname: lookoutstation-worker
        networks:
            - lookoutstationnet
        depends_on:
            - redis

    traefik:
        build: traefik/
        image: lookoutstation-traefik:latest
        container_name: lookoutstation-traefik
        hostname: lookoutstation-traefik
        networks:
            - web
        ports:
            - "80:80"
            - "443:443"
        labels:
            - "traefik.frontend.rule=Host:monitor.lookout.network"
            - "traefik.port=8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
