defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.dashboard]
    address = ":8080"
    [entryPoints.dashboard.auth]
      [entryPoints.dashboard.auth.basic]
        users = ["admin:$apr1$w4ZnFp0e$3/oZEdJhPq2gTW1WFqNT60"]

  [entryPoints.http]
    address = ":80"
      [entryPoints.http.redirect]
        entryPoint = "https"

  [entryPoints.https]
    address = ":443"
      [entryPoints.https.tls]
[api]
entrypoint="dashboard"

[acme]
email = "nelsoncabeteff@icloud.com"
storage = "acme.json"
entryPoint = "https"
onHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"

[docker]
domain = "lookout.network"
watch = true
network = "web"